### ISSUE TITLE
Not able to do Initial setup

### ISSUE THREAD

**Issue by vendra91** [andreaprosseda/vimar-byme-plus-homeassistant#10]
I've a domotic plant with thermostats and shutters and I've 01410 gateway. To comand everything by phone I use  the app VIMAR VIEW.

Following your guide I've install the VIEW PRO app (I didn't find VIMAR PRO) and I'm able to find my gateway but I can't select.

What can I do?

![image](https://github.com/user-attachments/assets/07b6dde0-5610-4385-92e6-909049ac0d2b)

**Comment by vendra91** [comment]
I solve the issue in another way.
Vimar VIEV have the possibility to integrate with third parts application (as HomeKit)
With this option I was able to connect directly the gateway by home assistant with the HomeKit integration

**Comment by CapexEV** [comment]
Hi, view pro is the app used by professionals for setup and, maybe, your electrician connected his account. If you would manage your system, you should ask him.

**Comment by andreaprosseda** [comment]
Hi @vendra91,

As @CapexEV mentioned, you need the appropriate privileges to add third-party integrations via Vimar View PRO. Without these, using this integration isn't possible. Your Vimar installer elettrician must have these privileges

HomeKit direct integration could be an alternative, but when I tested it, many entities either didn't work or were "not responding"
