### ISSUE TITLE
Failed setup

### ISSUE THREAD

**Issue by CapexEV** [andreaprosseda/vimar-byme-plus-homeassistant#12]
Hi, I followed every single step but I tried more and more but I have always same issue

When I put the setup code, HA shows me an affermative message; but when I go in "integration", the system gives me the message attached. When I rename the folder vimar_byme_plus in vimar_by_me_plus, the message goes off but the system still doen't find entities or device, even after a couples of hour.

### Environment
 - HomeAssistant Version: 2024.12.5 (same issue with 2024.11.3)

![Immagine 2024-12-27 010318](https://github.com/user-attachments/assets/d8295957-98c8-4f70-8c77-7ad3a48e550e)

**Comment by andreaprosseda** [comment]
Hi @CapexEV,
It seems you might have an entity (perhaps a light?) that is not currently supported yet.
I just released v1.6.1, which aims to address your error. This update should allow the integration to work, but if you can provide a log would be helpful to better understand the issue and, eventually, add new features.

I'm closing the issue, but feel free to reopen it it the error persists, or open a "request feature" for not implemented entities.
