### ISSUE TITLE
Gateway non trovato

### ISSUE THREAD

**Issue by ripe89** [andreaprosseda/vimar-byme-plus-homeassistant#6]
Credo di aver seguito scrupolosamente tutti i passaggi, anche avendo rimosso e preinstallato la repo piu volte ma finisce sempre che il gateway non viene trovato in automatico. Possiedo un 01411 con decine di dispositivi tra tapparelle, luci, sensori, ftv etc

Ho provato anche un aggiunta manuale, inserendo UID del gateway ed il suo IP ma la risposta che ottengo è IP_CONNECTOR_ERR_PERMISSION_DENIED

Un aiuto sarebbe suuuuuuuper gradito, grazie mille 😊

**Comment by ripe89** [comment]
Solved by trying again and by adding in manually

**Comment by andreaprosseda** [comment]
IP_CONNECTOR_ERR_PERMISSION_DENIED is usually the gateway response when the setup code is no longer valid.
When it happens, it is recommended to cancel the pending association and regenerate a new setup code from Vimar Pro
